services:
  - type: web
    name: blue-berry-ice-cream-backend
    env: python
    plan: free

    # On se place directement dans le dossier qui contient products.py + templates + static
    rootDir: backend/Blue_Berry_Ice_Cream

    # requirements.txt est à la RACINE → on remonte d’un cran
    buildCommand: python -m pip install --upgrade pip && pip install -r requirements.txt

    # App Flask = products dans products.py
    # Astuce : on peut appeler gunicorn via python -m (évite des soucis de PATH)
    startCommand: python -m gunicorn -w 2 -b 0.0.0.0:${PORT} products:products

    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6
      - key: FLASK_ENV
        value: production
      - key: DB_PATH
        value: /opt/render/project/src/data/blue_blerry_ice_cream.db

    disks:
      - name: bb-ice-cream-data
        mountPath: /opt/render/project/src/data

